### ISSUE TITLE
Feature request: relax input and output requirements, P2SH

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/spec#224]
In the context of the following lines:

> Has a single or the largest pay-to-pubkey-hash input by sum signed by the sending address
> 
> Any input not meeting the requirement for type (pay-to-pubkeyhash) will trigger the invalidation of the transaction
> 
> Only pay-to-pubkey-hash outputs will be considered for the reference address

Those requirements were introduced at some point to bring consensus without affecting history.

I'd like to propose the following:
1. Don't invalidate transactions with other input types. This is a low hanging fruit, given that there are very specific rules in place to determine the sender ("highest contribution by sum").
2. Consider pay-to-script-hash outputs as reference output.

This could be introduced at some block height in the future, because it would affect history otherwise.

The benefits of allowing any input type are far greater than P2SH, but the focus of this issue is to lay out a basis to support P2SH (escrow) recipients and senders.

**Comment by emmanuel-florent** [comment]
Please help: suppose Martin sent an Omni Asset (MaidCoin or TetherUSD) to a bitcoin address created for multisig (keys are owned by Bob and Alice). Is there a way to spend the asset or is it definitly burnt  ? Bob and Alice are willing to help/spend but they know they can't import two keys in omniwallet. Token is actually burn ? Guidance on how to use omni-core cli ?

**Comment by dexX7** [comment]
Hi @emmanuel-florent,

sending and receiving assets from P2SH/multisig is possible, and the tokens are not burned.

However, there is currently not a very handy way to do so. If you have all keys imported to Omni Core, then you should be able to send via the UI, but you can also use the CLI (e.g. with [omni_send](https://github.com/OmniLayer/omnicore/blob/omnicore-0.0.10/src/omnicore/doc/rpc-api.md#omni_send) or by crafting a [raw transaction](https://github.com/OmniLayer/omnicore/blob/omnicore-0.0.10/src/omnicore/doc/rpc-api.md#raw-transactions)).

If using Omni Core is currently not an option for you, please feel free to provide me with further information; I should be able to craft a raw transaction in the next days, which could then be signed by all parties.

**Comment by emmanuel-florent** [comment]
Ok so there is no impossibility at the protocol level so it's a nobility.
Unfortunatly I didn't find a lot of answer/documentation some maybe I can write some ?

1/ First need to setup like explained in [Omnicore Readme](https://github.com/OmniLayer/omnicore/blob/omnicore-0.0.10/README.md) is that it ?

2/ build a rawtransaction ? not sure how to do it ?
[Holding address](http://omnichest.info/lookupadd.aspx?address=3A3s2DFiRBJvdh8GVfVCeLaeeyTedg9fpa) 
Want to spend to 1CvGqy3fEL6pAYWjQb6f7ca9kUSmwXFSHy
Token ID 31.
3/ Instructions for Alice and/or Bob ?  
(ex: Alice send Private key to Bob is acceptable in that case)
Thanks a lot, I'll  try yo write the how-to as Alice asked for.

**Comment by dexX7** [comment]
Hey @emmanuel-florent,

there is a discussion about a related topic in this thread, which you may check out:

https://github.com/OmniLayer/omniwallet/issues/1314
