### ISSUE TITLE
Adopting the concept of BIPs: Mastercoin Protocol Improvement Proposals

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/spec#228]
The Mastercoin spec on GitHub and it's issue section appears to be the hub related to the discussion about:

- flaws in the current protocol
- inconsistencies in the current protocol
- evaluation of current features
- evaluation of planned features
- feature requests
- feature proposals
- ...

JR did an awesome job some time ago, when he cleaned up all open issues of the Mastercoin spec, but naturally over time the amount of open issues increased and given the general structure of GitHub's issue section some of the discussions get pretty much out of sight, once they become older or the related issues are closed.

I think it may be valuable to apply some kind of seperation, so that open issues mainly relate to the current specification and may, in the best case, be considered as an open tasks list. At the same time, in my opinion, there needs to be a place for discussion of planned or proposed protocol features, improvements and submission of such.

The developement around Bitcoin yielded a great amount of awesome ideas and approaches in general, but in particular (I think credit is due to Amir Taaki) there is a framework related to this context, called BIP or "Bitcoin Improvement Proposal". A detailed introduction and the process around BIPs can be found here:

https://github.com/bitcoin/bips/blob/master/bip-0001.mediawiki
https://github.com/bitcoin/bips

I was wondering about your thoughts about adopting a similar approach for Mastercoin - the basic idea is to create a new place for improvement proposals, evaluation and discussion in general. Defining a process for requesting features, e.g. for property issuers, crowdfunders or application designers who like to use the Master Protocol, but require feature X to do so, would also be valuable.

**Comment by msgilligan** [comment]
Well, two years and a rebrand later we are going to create Omni Layer Enhancement Proposals, to be known as *OLEs*. We have created a new Github repo for this purpose [OmniLayer/OLEs](https://github.com/OmniLayer/OLEs)

The plan is to create *OLE-001* to be a sample OLE (using BIP as a template) and to document the procedure. We are also planning on creating an OLE, probably *OLE-002* for the proposed Omni (Safe) Address format.

I suppose we can close this issue and continue discussion in the new repository?

**Comment by dexX7** [comment]
Sounds good to me! Thanks a lot for starting it! :)
