### ISSUE TITLE
Use blocktime to specify when an item in the spec takes effect

### ISSUE THREAD

**Issue by marv-engine** [OmniLayer/spec#260]
Using a block number as we do now is imprecise and it requires some last minute estimation to try to get close to the desired time. If we're shooting for a time why use a block number?

Using blocktime eliminates the error window and it can be set far in advance. It's also easier for humans to remember a timestamp rather than a blocknumber. I believe bitcoin client code uses blocktime for this purpose.

**Comment by msgilligan** [comment]
@marv Now that we have the OLE process, once an OLE gets final approval, an "effective at block height" field should be set in the OLE header.

**Comment by msgilligan** [comment]
@marvgmail @dexX7 @achamely @CraigSellars I think we should close this issue.
