### ISSUE TITLE
Move 'spec' Github repo to OmniLayer Github organization

### ISSUE THREAD

**Issue by msgilligan** [OmniLayer/spec#306]
Now that the [omnicore](https://github.com/OmniLayer/omnicore) repo is in the [OmniLayer](https://github.com/OmniLayer) organization, this `spec` repo should be moved over there, too.

**Comment by msgilligan** [comment]
@achamely @zathras-crypto @dexX7 @DavidJohnstonCEO @CraigSellars @marv-engine Isn't it time to move the `spec` repo over to the new [OmniLayer](https://github.com/OmniLayer) Github organization.

**Comment by dexX7** [comment]
+1

There is no reason not to do it.

**Comment by zathras-crypto** [comment]
+1

**Comment by achamely** [comment]
done
