### ISSUE TITLE
Rename Specification to Omni Protocol Specification

### ISSUE THREAD

**Issue by msgilligan** [OmniLayer/spec#308]
Omni Protocol or Omni Layer?

**Comment by msgilligan** [comment]
@CraigSellars @marv-engine @achamely @zathras-crypto @dexX7 

Any thoughts on what he new name should be? If there's consensus, I'll create a pull request.

**Comment by dexX7** [comment]
What do you think sounds right? I almost tend to believe the most accurate wording would be "Omni Layer Protocol", but it's aweful.

Did you see the old description?

---

- The term M.A.S.T.E.R. is an acronym for "Metadata Archival by Standard Transaction Embedding Records"
- The term "Master Protocol" applies to the specification and the clients that implement its features.
- The term "MSC Protocol" is used as the abbreviation for "Master Protocol".
- The term "Mastercoins" applies to the digital tokens that access the features of the "Master Protocol" clients.
- The term "MSC" is used as the abbreviation for "Mastercoins".

The “Master Protocol” layer between the existing Bitcoin Protocol and users’ currencies is [...]

---

**Comment by msgilligan** [comment]
My preference is to call the Protocol, the 'Omni Protocol' and to call the Protocol + implementation + ecosystem the "Omni Layer".

So I would make the title: **Omni Protocol Specification**

And yes, the whole terminology section will need updating, too.

**Comment by dexX7** [comment]
Sounds fine in my opinion.

**Comment by zathras-crypto** [comment]
Honestly I'm ambivalent here guys - marketing was never my strongpoint so whatever nomenclature you think suits best is fine by me :)

**Comment by marvgmail** [comment]
@msgilligan I agree with your definitions for Omni Protocol and Omni Layer.

**Comment by msgilligan** [comment]
Sounds like we have enough consensus were I can start work on a pull request. We can discuss and refine the specifics on the pull request.

**Comment by achamely** [comment]
+1, you've got my vote

**Comment by msgilligan** [comment]
OK, PR #309 is now open and we can continue the discussion there.

Note: My suggestion is that we agree on title and terminology first, then someone (I volunteer) can go through the Spec and update everything to the new terminology.

**Comment by msgilligan** [comment]
Closing now that PR #309 is merged.
