### ISSUE TITLE
Rebrand Currency/Token from Mastercoin (MSC) to Omni (OMNI)

### ISSUE THREAD

**Issue by msgilligan** [OmniLayer/spec#312]
Now that all occurrences in the Spec of _Master_ or _Mastercoin_ other than those referring to the currency/token (or are historical references) have been changed to _Omni_, it's time for a discussion of whether to rename the token and how it should be done.

I don't have a strong opinion one way or the other, but if you read through the current Spec you'll see many occurrences of _Mastercoin_ and _Mastercoins_ and I do find it a little jarring. There is also the particular case of what we call the Real/Live/Production/Mastercoin/MSC Ecosystem vs. the Test/TMSC Ecosystem.

**Comment by patrickdugan** [comment]
My opinion is we should rebrand to "Omni tokens", or "Omnis", and the OMNI symbol for use the Dex and other exchanges where it is traded. I believe Craig said about 6 months ago that it's easy to change the strings associated with the #1 smart property. The connotation of OMNI as a monetary commodity is much slicker, more futuristic and so on than Mastercoins or MSC.

**Comment by davidpbrown** [comment]
Reading this as no change for holders of MSC and just a trivial name fix, which would make sense if Omni is to become a strong brand. On the upside, such a change might encourage people to look again at what Omni's potential is; so, be sure to couple with a clear statement of what the ambitions are now.. we see updates but is there a mission|vision statement and milestones or equivalent.. something that is a point of reference?

**Comment by dexX7** [comment]
@davidpbrown: +1

Thanks for the feedback. I agree here, defining a new mid and long term roadmap would be great, and this should be reevaluated from time to time.

I'm split regarding the name of the tokens. I never really liked "Omni", mostly because I was pretty amazed, after I realized "Master" wasn't arbitary, but an acronym for "metadata archival by standard transaction embedding records".

The rebranding is one side, and I see why it makes sense, but I'm split about renaming the tokens, because one base assumption is that historical state is immutable. This is a weak argument, because the token name is purely cosmetic, but still ... I kinda like "MSC", I guess.

**Comment by davidpbrown** [comment]
Yes, Omni was an odd choice over MasterCoin brand but in for a penny, in for a pound. If there was a basis to change to Omni, then perhaps it's worth following through.. as much as I saw, was some attempt to suggest it is a platform but it's not been a strong launch and the community and activity has dropped away. Omni is not an obvious name for all the allusion to 'all powerful' that I suppose prompted it; so, setting out clearly what it will do - what problem it solves and making clear how it is used will be important.

If Omni is made trivial to understand and use, that could be all the edge that's needed. Too many alternates I wonder are being too ambitious and then appealing only to those strongly engaged enough to understand it.

If Omni is to live up to its name and do "all things", then perhaps it needs to address the default interests users will have in wanting one wallet/platform that can cater for all their cypto-currency and assets; some capability to acknowledge CounterParty assets and others might help simplify mainstream confusion.

Off-topic: I wonder having no forum doesn't help those of us who are interested understand where devs thinking is at. If a new forum is setup, The Discourse forum software is best atm.

**Comment by dexX7** [comment]
Has been done.
