### ISSUE TITLE
Best solutions to list USDT on an exchange?

### ISSUE THREAD

**Issue by trungnq1510** [OmniLayer/spec#318]
I am build an exchange which allow user can deposit, withdraw, and trading to others crypto currency. 
I create an Omni node to verify omni transactions. When user want to deposit, I create an address for deposit. After user deposit successful, I must to send bitcoin which equal to two transaction fees to the deposit address to send all USDT to the master USDT address. Is there any better solutions?

**Comment by dexX7** [comment]
Hi, please check out:

https://github.com/OmniLayer/omnicore/wiki/Platform-Integration-of-Omni-Core

**Comment by initsysctrl** [comment]
after v0.3.1,Omni core provide a new rpc-api to set a fee address,you can see it ["send_funded_all"](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_funded_sendall)
