### ISSUE TITLE
A transaction send USDT(version:0.13) to BTC(version:0.16) address,How to transfer out from BTC address?

### ISSUE THREAD

**Issue by kanliyong** [OmniLayer/spec#319]
## A transaction send USDT(version:0.13) to BTC(version:0.16) address,How to transfer out from BTC address?

- I try import private key into OMNI ,but can not recognition that private key.

Any one have ideas ?

**Comment by dexX7** [comment]
Hi @kanliyong, just to clarify: did you try to import the private key into omniwallet.org?

**Comment by kanliyong** [comment]
@dexX7 
I try to import the private key into my local omni node.Then the omni layer can not recognition that private key.

**Comment by achamely** [comment]
@kanliyong what format is the private key that you get from bitcoin core 0.16? 
Does it start with `5`, `K`, or `L` or does it start with something like `xprv` ?
Also does your address start with `1`, `3`, `bc1`  ?

**Comment by kanliyong** [comment]
@achamely 
Hi !

My receive address is **34mzLiPmSGxwAe6sCDkxZTAn25hThBCmZn**

**Comment by achamely** [comment]
@kanliyong ok so you have a segwit address. No matter what you do when you import that private key into a .13 client it will not give you the same address because segwit support was added in 0.16. 

What you can do is import the private key into electrum , which supports segwit, then following this guide from the section titled 'Recover Tokens Using Electrum' https://github.com/OmniLayer/omniwallet/wiki/Recovering-funds-stuck-on-a-Trezor-or-Electrum-address#recover-tokens-using-electrum

To recover the funds off that address and back to an address in your Omniwallet.org account or a USDt deposit address on an exchange you control

**Comment by kanliyong** [comment]
@achamely  Thank you very much!

I will have a try!

**Comment by kanliyong** [comment]
@achamely Thank you very much!

I have done success ! but a different import private key way.

- create a wallet kind of **Import Bitcoin addresses or private keys**
- import bitcoin address private key start with : **p2wpkh-p2sh:**
- Tools->Pay to many , copy follow code to input
```
OP_RETURN 6f6d6e690000000401, 0
Your-Omni-Protocol-Enabled-Recovery-Destination-address, 0.00000546
```
- Other details check out [https://github.com/OmniLayer/omniwallet/wiki/Recovering-funds-stuck-on-a-Trezor-or-Electrum-address#recover-tokens-using-electrum](https://github.com/OmniLayer/omniwallet/wiki/Recovering-funds-stuck-on-a-Trezor-or-Electrum-address#recover-tokens-using-electrum)

- then sign ,broadcasting  

This transition type is omni  send all [https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_sendall](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_sendall)

<img width="594" alt="wx20180905-122221 2x" src="https://user-images.githubusercontent.com/2900472/45071131-66a86700-b107-11e8-9c0c-b0f6e61e575d.png">
<img width="603" alt="wx20180905-122252 2x" src="https://user-images.githubusercontent.com/2900472/45071143-6f993880-b107-11e8-98c5-abcbfbcea8c4.png">
<img width="841" alt="wx20180905-122513 2x" src="https://user-images.githubusercontent.com/2900472/45071145-732cbf80-b107-11e8-8892-f62b0798b475.png">

**Comment by achamely** [comment]
@kanliyong Thanks for the update. We've created a new wiki support article that details this updated information for others to use in the future: https://github.com/OmniLayer/omniwallet/wiki/Recovering-funds-from-a-Segwit-Address
