### ISSUE TITLE
TetherUS - USDT guide ?

### ISSUE THREAD

**Issue by kmacblad** [OmniLayer/spec#321]
We are game developer. Now we want to receive & send TetherUS - USDT (Omni Layer Protocol) coin  between diff accounts.
Can I use your library & apis to do this ?

Thanks for your support

**Comment by dexX7** [comment]
Hi,

you can use Omni Core, our reference client, for this:

https://github.com/OmniLayer/omnicore/wiki/Platform-Integration-of-Omni-Core
