### ISSUE TITLE
Why are 32 bits of Property ID enough?

### ISSUE THREAD

**Issue by luongnguyenduc** [OmniLayer/spec#327]
As I read, anyone can create properties in Omni layer, what prevent a person from writing a loop to create many properties and use all the available IDs in the range?

**Comment by dexX7** [comment]
Hey @luongnguyenduc,

to create an Omni transaction, a Bitcoin transaction is created, which costs a certain fee. To allocate "all" numbers would be massively expensive. There can be up to 4,294,967,295 unique identifiers and if we run out of them, we can update the protocol to allow more.
