### ISSUE TITLE
Convert Specification to AsciiDoc from Markdown

### ISSUE THREAD

**Issue by msgilligan** [OmniLayer/spec#333]
In our weekly meetings, we've agreed that we want to convert the specification from markdown format to [AsciiDoc(tor)](https://asciidoctor.org) format.

I've created a DRAFT pull request PR #329  to do this, but I wanted to have a little discussion about how best to merge the changes. I've also created PR #332 to convert the other documents in this repo.

The [Omni Documentation repo](https://github.com/OmniLayer/Documentation) is already in AsciiDoc format and *Getting Started with Omni Development* now includes a [Working with Asciidoctor format](https://github.com/OmniLayer/Documentation/blob/master/developer/OmniDev_GettingStarted.adoc#working-with-asciidoctor-format) section.

My proposal is that we do the following:

1. Merge PR #335
2. Rebase the two outstanding PRs with Github-markdown formatted changes (PR #313 and PR #316) to the updated `master` branch.
3. Add additional commits to PR #313 and PR #316 that convert the changes in the PR to AsciiDoc format.
4. Merge PR #329 To enable Github Actions to generate PDF and downloadable HTML versions of the Spec.

If consensus forms around this approach, I'll make it happen.

@CraigSellars @achamely @marvgmail @dexX7

**Comment by achamely** [comment]
#332 looks good to me and i'm on board with this approach

**Comment by msgilligan** [comment]
OK, PR #335 is merged.
PR #329 is ready for review/merge.
And I've submitted a PR to @marvgmail to update is OmniDex 2 PR to AsciiDoc format.

**Comment by msgilligan** [comment]
The conversion is complete. Additional work remains to get PR #313 and PR #316 merged, but we don't need this issue open to track that.
