### ISSUE TITLE
Allowing combining multiple inputs in a single transaction

### ISSUE THREAD

**Issue by ripper234** [OmniLayer/spec#77]
According to @dacoinminster, currently it is not possible to do a simple send that combines multiple inputs (possibly only for inputs with different addresses - J.R can you clarify this point?).

This means that a user that have multiple inputs in his wallets with different balances, he would need to create multiple send operations (and pay more fees) in order to send these funds. Also the recipient will then have multiple inputs himself, and will have to spend more fees to move them.

I think this should be addressed at the spec level first, and then added in the various wallets.

**Comment by shalakhin** [comment]
So, is that possible having X addresses to combine inputs and send it to some address?

i.e. we have 5 addresses and want to send all of the funds to another address. As I understand from this thread I will have to make 5 transactions paying fees 5 times.
